### ISSUE TITLE
ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by shekharIT** [pytorch/glow#3829]
Hi, Help us to solve this issue....

Error Logs:An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.io.FileNotFoundException: tests/unit/src/com/android/bluetooth/btservice/storage/schemas/com.android.bluetooth.btservice.storage.MetadataDatabase/102.json (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at androidx.room.migration.bundle.SchemaBundle.serialize(SchemaBundle.java:100)
        at androidx.room.vo.Database.exportSchema(Database.kt:100)
        at androidx.room.RoomProcessor$DatabaseProcessingStep.process(RoomProcessor.kt:169)
        at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
        at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
[ 10% 8649/80599] AAPT2 link out/target/product/generic_arm64/obj/APPS/Dialer_intermediates/package-res.apk
warn: removing resource com.android.dialer:string/main_call_history_tab_description without required default value.
warn: removing resource com.android.dialer:string/main_send_feedback without required default value.
warn: removing resource com.android.dialer:string/nui_shortcut_name without required default value.
[ 10% 8650/80599] //packages/modules/CaptivePortalLogin:CaptivePortalLogin r8 [common]
[ 10% 8651/80599] //frameworks/base/packages/OsuLogin:OsuLogin r8 [common]
[ 10% 8652/80599] //packages/apps/Gallery2:Gallery2 r8 [common]
[ 10% 8653/80599] //frameworks/base/packages/Shell:Shell r8 [common]
Warning: Library class android.os.BugreportManager$DumpstateListener extends program class android.os.IDumpstateListener$Stub
[ 10% 8654/80599] //frameworks/base/packages/PackageInstaller:PackageInstaller r8 [common]
[ 10% 8655/80599] //packages/inputmethods/LatinIME/java:LatinIME r8 [common]
ninja: build stopped: subcommand failed.
ninja failed with: exit status 1

**Comment by shekharIT** [comment]
Can anyone have idea about the above issues?

**Comment by jfix71** [comment]
@shekharIT This doesn't look like you're building Glow at all. Not really sure what's going on here/how to help. Can you verify what exactly you did to build Glow that got you to this point?

**Comment by shekharIT** [comment]
I have cloned aosp source code and try to build but every time I am getting
the same issue.

Step i have followed
1. Source  build/envsetup.sh
2. Lunch and selected the board
3. Make -j

After followed the above step and faced the same error.

Thanks

**Comment by jfix71** [comment]
Seems you're commenting on the wrong repo -- Glow has nothing to do with AOSP, so we can't help here, sorry!
